name: Mirror to Private GitLab

on:
  push:
    branches:
      - main  # Le miroir se déclenche uniquement quand vous modifiez la branche main
  delete:

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Push to GitLab Server
        run: |
          # Commande de push vers votre serveur spécifique
          git push --mirror http://oauth2:${{ secrets.GITLAB_HOUSEWORK_TOKEN }}@72.61.180.240:9080/housework/housework-app.git
